# Generated by Django 3.2.16 on 2024-03-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedimage',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
