# Generated by Django 3.2.16 on 2024-03-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_analyzedimage_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedimage',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedimage',
            name='user_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
